CREATE SEQUENCE pc.products_sequence MINVALUE 1 START 1 INCREMENT BY 1;

INSERT INTO pc.products (product_id, name, description, price, image_url)
VALUES
    (nextval('pc.products_sequence'),
     'Retail Short Term Insurance',
     'Provides cover for short-term products for individuals - Electronics,Household Items, Jewellery, Cars etc.',
     500.00, null),
    (nextval('pc.products_sequence'),
     'Retail Long-Term Insurance',
     'Provides cover for longer term products individuals - household insurance, life insurance etc.',
     1000.00, null),
    (nextval('pc.products_sequence'),
     'Commercial Short Term Insurance',
     'Provides cover for short-term products for commercial entities - Printers, Company Cars, Theft, etc.',
     5000.00, null),
    (nextval('pc.products_sequence'),
     'Commercial Long-Term Insurance',
     'Provides cover for longer term products - office insurance, employee benefit insurance, etc.',
     1000.00, null),
    (nextval('pc.products_sequence'),
     'Device Contract',
     'Allows the customer to take out a device on contract - such as a phone, laptop etc.',
     850.00, null),
    (nextval('pc.products_sequence'),
     'Short-Term Investment Product',
     'Provides a way for customers to invest their money over a short period of time - 32 day fixed deposit etc.',
     2500.00, null),
    (nextval('pc.products_sequence'),
     'Long-Term investment Product',
     'Provides a way for users to invest their money over the long term - Retirement / Annuity Funds, Unit Trusts etc',
     5000.00, null),
    (nextval('pc.products_sequence'),
     'Islamic Investment Product',
     'Provides a way for Islamic customers to invest their money',
     5000.00, null),
    (nextval('pc.products_sequence'),
     'VIP Investment Product',
     'Provides an Investment product for VIP customers Over 150 Million Net-Asset Value',
     2000.00, null);