openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8085
    description: Generated server url
paths:
  /token:
    post:
      tags:
        - authentication-controller
      operationId: token
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
