jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
spring:
  datasource:
    url: jdbc:postgresql://devcamp-db:5432/postgres
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    ignore-migration-patterns: "*:missing"
    schemas: pc
    default-schema: pc
  jpa:
    hibernate:
      ddl-auto: none
springdoc:
  show-actuator: false
management:
  endpoints:
    web:
      exposure:
        include: "*"