openapi: "3.0.0"

info:
  version: "1.0.0"
  title: "Fulfilment"
  license:
    name: "MIT"

servers:
  - url: "http://localhost:8086/v1"

paths:
  /stuff:
    get:
      summary: Get stuff
      responses:
        '200':
          description: Successful response